"""create initial banking schema

Revision ID: 8c705667f479
Revises: 
Create Date: 2026-05-20 16:17:50.281959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c705667f479'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.Enum('INDIVIDUAL', 'CORPORATE', name='clienttype'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    op.create_table('credit_types',
    sa.Column('credit_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.Enum('CONSUMER', 'MORTGAGE', name='credittypename'), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.CheckConstraint('interest_rate > 0', name='check_interest_rate_positive'),
    sa.CheckConstraint('max_amount > 0', name='check_max_amount_positive'),
    sa.CheckConstraint('max_term_months > 0', name='check_max_term_months_positive'),
    sa.PrimaryKeyConstraint('credit_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_credit_types_credit_type_id'), 'credit_types', ['credit_type_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='check_account_balance_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('iban')
    )
    op.create_index(op.f('ix_bank_accounts_account_id'), 'bank_accounts', ['account_id'], unique=False)
    op.create_table('corporate_clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('eik', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('eik')
    )
    op.create_table('individual_clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('egn', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('egn')
    )
    op.create_table('loan_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('requested_term_months', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('application_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='loanapplicationstatus'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('credit_type_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('requested_amount > 0', name='check_requested_amount_positive'),
    sa.CheckConstraint('requested_term_months > 0', name='check_requested_term_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['credit_type_id'], ['credit_types.credit_type_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_loan_applications_application_id'), 'loan_applications', ['application_id'], unique=False)
    op.create_table('loans',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAID', 'OVERDUE', 'CLOSED', name='loanstatus'), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('principal_amount > 0', name='check_principal_amount_positive'),
    sa.CheckConstraint('term_months > 0', name='check_loan_term_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.application_id'], ),
    sa.PrimaryKeyConstraint('loan_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_loans_loan_id'), 'loans', ['loan_id'], unique=False)
    op.create_table('mortgage_details',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('property_address', sa.String(length=255), nullable=False),
    sa.Column('property_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('down_payment >= 0', name='check_down_payment_not_negative'),
    sa.CheckConstraint('property_value > 0', name='check_property_value_positive'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('repayment_plans',
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_part', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_part', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('installment_number > 0', name='check_installment_number_positive'),
    sa.CheckConstraint('interest_part >= 0', name='check_interest_part_not_negative'),
    sa.CheckConstraint('principal_part >= 0', name='check_principal_part_not_negative'),
    sa.CheckConstraint('remaining_balance >= 0', name='check_remaining_balance_not_negative'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], ),
    sa.PrimaryKeyConstraint('installment_id'),
    sa.UniqueConstraint('loan_id', 'installment_number', name='uq_loan_installment_number')
    )
    op.create_index(op.f('ix_repayment_plans_installment_id'), 'repayment_plans', ['installment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayment_plans_installment_id'), table_name='repayment_plans')
    op.drop_table('repayment_plans')
    op.drop_table('mortgage_details')
    op.drop_index(op.f('ix_loans_loan_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_loan_applications_application_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_table('individual_clients')
    op.drop_table('corporate_clients')
    op.drop_index(op.f('ix_bank_accounts_account_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_credit_types_credit_type_id'), table_name='credit_types')
    op.drop_table('credit_types')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
