"""add representative name to corporate clients

Revision ID: 9afadee42c93
Revises: fe44b907be86
Create Date: 2026-06-19 22:39:10.285651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afadee42c93'
down_revision: Union[str, Sequence[str], None] = 'fe44b907be86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_clients', sa.Column('representative_name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_clients', 'representative_name')
    # ### end Alembic commands ###
